name = "MathOptChordalDecomposition"
uuid = "691ff971-50ce-4a2e-a182-eb537bf792c3"
authors = ["Richard Samuelson <rsamuelson@ufl.edu>"]
version = "0.2.0"

[deps]
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CliqueTrees = "1.5.1"
Graphs = "1.12.1"
LinearAlgebra = "1.10"
MathOptInterface = "1.39"
SparseArrays = "1.10"
julia = "1.10"
